aconv-chans: 10
aconv-filts: 100
adim: 320
atype: dot
batch-size: 20
dlayers: 1
dropout-rate: 0.1
dunits: 300
elayers: 3
epochs: 100
eprojs: 320
etype: blstmp
eunits: 320
maxlen-in: 800
maxlen-out: 150
mtlalpha: 1.0
opt: adadelta
patience: 3
sampling-probability: 0.1
subsample: '1_2_2_1_1'
